openapi: 3.0.3
info:
  title: Swagger - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:4000
tags:
  - name: users
    description: Threads replica users APIs 
  - name: posts
    description: Treads replica posts API
  - name: bookmark
    description: Threads replica bookmarks APIs
  - name: like
    description: Threads replica like APIs

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Register
      description: 'Register Threads Replica'
      operationId: register
      requestBody: 
        description: Registration Information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
        required: true
      responses:
        default:
          description: Register successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                   message:
                    type: string
                    example: Register successfully
                    $ref: '#/components/schemas/SuccessAuthentication'
        '422':
          description: Invalid input
  /users/login:
    post:
      tags:
        - users
      summary: Login
      description: 'Login to Threads Replica'
      operationId: login
      requestBody: 
        description: Login Information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
        required: true
      responses:
        default:
          description: Login successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                   message:
                    type: string
                    example: Login success
                    $ref: '#/components/schemas/SuccessAuthentication'
        '422':
          description: Invalid input
  /users/me:
    get:
      tags:
        - users
      summary: Get my profile
      description: Get my profile
      operationId: getMe
      security:
        - BearerAuth: []
      responses:
        default:
          description: Get user profile successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/forgot-password:
    post:
      tags:
        - users
      summary: Forgot password
      description: 'Forgot password'
      operationId: forgotPassword
      requestBody: 
        description: Forgot password information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordBody'
      responses:
        default:
          description: Forgot password Information
          content:
            application/json:
              schema:
                type: object
                properties:
                   message:
                    type: string
                    example: Check email to reset password
        '422':
          description: Invalid input
  /bookmark:
    post:
      tags:
        - bookmark
      summary: Bookmark a post
      description: Bookmark a post
      operationId: bookmarkPost
      security:
        - BearerAuth: []
      requestBody: 
        description: Bookmark information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookmarkBody'
      responses:
        default:
          description: Bookmark post successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                   message:
                    type: string
                    $ref: '#/components/schemas/Bookmark'
        '422':
          description: Invalid input
  /like:
    post:
      tags:
        - like
      summary: Like a post
      description: Like a post
      operationId: likePost
      security:
        - BearerAuth: []
      requestBody: 
        description: Bookmark information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LikeBody'
      responses:
        default:
          description: Like post successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                   message:
                    type: string
                    $ref: '#/components/schemas/Like'
        '422':
          description: Invalid input
          